name: rmp
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotli=1.0.9
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - cycler=0.11.0
  - fonttools=4.25.0
  - freetype=2.10.4
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9d
  - kiwisolver=1.3.2
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp=1.2.2
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1n
  - packaging=21.3
  - pillow=9.0.1
  - pip=21.2.4
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.9.12
  - python-dateutil=2.8.2
  - qt=5.9.7
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.38.2
  - tk=8.6.11
  - tornado=6.1
  - tzdata=2022a
  # - vc=14.2
  # - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  # - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - kdtree==0.16
# prefix: C:\Users\Darie\miniconda3\envs\rmp
